Selection Tookit package v1/retrieveOutput/objects/Anchor__c.object
<CustomObject>
    <description>This object include pre-defined anchors</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Anchor__c</fullName>
        <label>Anchor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessor__c</fullName>
        <label>Assessor</label>
        <picklist>
            <picklistValues>
                <fullName>People Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hiring Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Key Challenger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cultural Bar Raiser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Function</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EBM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Competency__c</fullName>
        <label>Competency</label>
        <picklist>
            <picklistValues>
                <fullName>Introduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dream Big</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Develop People</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live Our Culture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interest And Ambition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Functional Achievements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry Knowledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Socio Economic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecting The Dots</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Functional Challenge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Anchor</label>
    <nameField>
        <displayFormat>ANC-{0000}</displayFormat>
        <label>Anchor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Anchors</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Selection Tookit package v1/retrieveOutput/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Candidate_Name__c</fullName>
        <description>Enter the name of the candidate</description>
        <label>Candidate Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overall_Score__c</fullName>
        <formula>(IF(ISNULL(People_Manager_Score__c),0,People_Manager_Score__c) + IF(ISNULL(Hiring_Manager_Score__c),0,Hiring_Manager_Score__c) + if(ISNULL(Key_Challenger_score__c),0,Key_Challenger_score__c)+ IF(ISNULL(Cultural_Bar_Raiser_score__c),0,Cultural_Bar_Raiser_score__c)+ IF(ISNULL(Head_Of_Function_score__c),0,Head_Of_Function_score__c )+ IF(ISNULL(EBM_score__c),0,EBM_score__c))
/
(If(People_Manager_Score__c =0 ,0,1) + IF(Hiring_Manager_Score__c =0,0,1)+if(Key_Challenger_score__c =0,0,1)+if(Cultural_Bar_Raiser_score__c=0,0,1)+if(Head_Of_Function_score__c=0,0,1)+if(EBM_score__c=0,0,1))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Overall Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Application Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People Manager Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hiring Manager Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Key Challenger Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cultural Bar Raiser Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Function Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EBM Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candidate Hired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candidate Did Not Pass</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CAN-{000000}</displayFormat>
        <label>Candidate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Selection Tookit package v1/retrieveOutput/objects/Interview__c.object
<CustomObject>
    <description>This object include interview records</description>
    <fields>
        <fullName>Candidate_Name__c</fullName>
        <label>Candidate Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Interviews</relationshipLabel>
        <relationshipName>Interviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Interviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunities__c</fullName>
        <label>Opportunities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Overall_Score1__c</fullName>
        <formula>(Score_1__c  + Score_2__c + Score_3__c) / 3</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Overall Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overall_Score__c</fullName>
        <label>Overall Score</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recruitment_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recruitment Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Recruitment_Coordinators</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score_1__c</fullName>
        <label>Score 1</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_2__c</fullName>
        <label>Score 2</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_3__c</fullName>
        <label>Score 3</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_4__c</fullName>
        <label>Score 4</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selected_Anchors__c</fullName>
        <label>Selected_Anchors</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Selected_Question_1__c</fullName>
        <label>Selected Question 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Selected_Question_2__c</fullName>
        <label>Selected Question 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Selected_Question_3__c</fullName>
        <label>Selected Question 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Selected_Question_4__c</fullName>
        <label>Selected Question 4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Strengths__c</fullName>
        <label>Strengths</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Interview</label>
    <nameField>
        <displayFormat>INT-{0000000}</displayFormat>
        <label>Interview Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Selection Tookit package v1/retrieveOutput/objects/Interview_Section_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Anchor_Assessor__c</fullName>
        <label>Anchor Assessor</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessor__c</fullName>
        <label>Assessor</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Competency__c</fullName>
        <label>Competency</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Has_Anchor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Anchor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Intro__c</fullName>
        <label>Intro</label>
        <type>TextArea</type>
    </fields>
    <label>Interview Section Settings</label>
</CustomObject>

Selection Tookit package v1/retrieveOutput/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Position</label>
    <nameField>
        <displayFormat>POS-{000000}</displayFormat>
        <label>Position Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Selection Tookit package v1/retrieveOutput/objects/Question__c.object
<CustomObject>
    <description>This object include pre-defined questions</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assessor__c</fullName>
        <label>Assessor</label>
        <picklist>
            <picklistValues>
                <fullName>People Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hiring Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Key Challenger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cultural Bar Raiser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Function</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EBM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Competency__c</fullName>
        <label>Competency</label>
        <picklist>
            <picklistValues>
                <fullName>Introduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dream Big</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Develop People</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live Our Culture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interest And Ambition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Functional Achievements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry Knowledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Socio Economic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecting The Dots</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Functional Challenge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insights</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Selection Tookit package v1/retrieveOutput/classes/Interview_Controller.cls
/**
 *     @author:  Tomer Glicksman (tglixman@salesforce.com)
 *     @since:   2016-05-29
 *     @desc:    Controller for interview page
 *     @history: 
 */

public with sharing class Interview_Controller {
    public String introduction                                      {get;set;}
    public List<Candidate__c> candidate                             {get;set;}
    public String yourRecordId                                      {get;set;}
    public List<SectionData> sectionDataList                        {get;set;}    
    public List<Integer> numbersList                                {get;set;}
    public Interview__c rec                                         {get;set;}
    public Boolean editMode                                         {get;set;}
    public List<Attachment> attachmentsList                         {get;set;}
    public List<Interview__c> previousInterviews                    {get;set;}
    public static String interviewStr                               {get;set;}
    public Map<String,Decimal> textareaMinimumChar                  {get;set;}

    /**
     *     @desc:    Ctor. initializing data.
     *     @param    activityController - standard controller
     */
    public Interview_Controller(ApexPages.StandardController stdcontroller){
        editMode = false;
        String yourRecordId = ApexPages.currentPage().getParameters().get('id');
        rec = getCurrentRecord(yourRecordId);
        system.debug('rec ctor=' + rec);
        String currentRecordType = rec.RecordType.Name;

        List<Question__c> queryResult = [select Question__c, Competency__c from Question__c WHERE Assessor__c=:currentRecordType AND Competency__c='Introduction' AND Active__C=True];
        introduction = queryResult[0].Question__c;

        sectionDataList = getSectionDataList(currentRecordType);

        numbersList = new List<Integer> { 1,2,3,4,5,6,7,8,9 };
        attachmentsList = getAttachments(rec.Candidate__c);
        previousInterviews = getPreviousInterviews(rec.Candidate__c,rec.Id);

        textareaMinimumChar = getTextareaMinimumChars();
        system.debug('textareaMinimumChar:' + textareaMinimumChar);
    }

    /**
     *      @desc:    getting interview record by given id
     *      @param    id: the interview id
     *      @return   interview record
     */
    public Interview__c getCurrentRecord(String id) {
        return [SELECT Status__c,
                        Interviewer__c,
                        Recruitment_Coordinator__c,
                        Candidate__c,
                        Candidate_Name__c,
                        RecordType.Name,
                        Score_1__c,
                        Score_2__c,
                        Score_3__c,
                        Score_4__c,
                        Selected_Anchors__c,
                        Selected_Question_1__c,
                        Selected_Question_4__c,
                        Selected_Question_3__c,
                        Selected_Question_2__c,
                        Overall_Score1__c,
                        Overall_Score__c,
                        Notes__c,
                        Opportunities__c,
                        Strengths__c
                        FROM Interview__c WHERE Id=:id][0];
    }

    /**
     *      @desc:    getting attachments of the candidate
     *      @param    candidateId: the candidate record id
     *      @return   list of the candidate attachments
     */
    private List<Attachment> getAttachments(String candidateId) {
        List<Attachment> retVal = new List<Attachment>();
        retVal = [SELECT Id, Name, Description, LastModifiedDate, CreatedBy.Name FROM Attachment WHERE ParentId =: candidateId];
        return retVal;
    }

    /**
     *      @desc:    getting the sections data for this specific type of interview
     *      @param    assessor: the interview record type
     *      @return   list of sections settings
     */
    @TestVisible private List<SectionData> getSectionDataList(String assessor) {
        List<SectionData> retVal = new List<SectionData>();               
        List<Interview_Section_Settings__c> sectionSettingsList = [SELECT Intro__c, Assessor__c, Competency__c, Has_Anchor__c, Anchor_Assessor__c FROM Interview_Section_Settings__c WHERE Assessor__c =: assessor AND Is_Active__c = True];
        for (Interview_Section_Settings__c sectionSettings: sectionSettingsList) {
          SectionData sectionData = new sectionData(sectionSettings);
          retVal.add(sectionData);
        }      

        return retVal;
    }

    /**
     *      @desc:    getting minimun characters required for the textareas on the interview page
     *      @return   a mapping between the textarea id and its minimum chars
     */
    private Map<String,Decimal> getTextareaMinimumChars() {
        Map<String,Decimal> retVal = new Map<String,Decimal>();
        List<Textarea_Minimum_Chars__c> minCharList = [SELECT Minimum_Chars__c, Text_Area_Id__c FROM Textarea_Minimum_Chars__c WHERE Is_Active__c = True AND Page_Name__c = 'Interview_View'];
        for (Textarea_Minimum_Chars__c minChar: minCharList) {
           retVal.put(minChar.Text_Area_Id__c,minChar.Minimum_Chars__c);
        }
        return retVal;
    }

    /**
     *      @desc:    getting the previous interviews of the candidate, in order to get notes, opps and strengths from those interviews
     *      @param    candidateId: the candidate
     *      @param    currentInterviewId: the current interview record id     
     *      @return   list of sections settings
     */
    private List<Interview__c> getPreviousInterviews(String candidateId,String currentInterviewId) {
        List<Interview__c> retVal = new List<Interview__c>();
        List<Interview__c> interviews = [SELECT CreatedDate,Notes__c,Strengths__c,Opportunities__c,Interviewer__c,Position__c,Interview_Date__c,RecordType.Name FROM Interview__c WHERE Candidate__c =: candidateId AND Id !=: currentInterviewId];
        for (Interview__c interview:interviews) {
            if ((interview.Notes__c != null && interview.Notes__c != '') || (interview.Opportunities__c != null && interview.Opportunities__c != '') || (interview.Strengths__c != null && interview.Strengths__c != '')) {
                retVal.add(interview);
            }
        }
        return retVal;
    }

    /**
     *      @desc:    an object that represents a single section full data, including its anchors for each type
     */
    public class SectionData {
      public String             sectionIntro        {get; private set;}
      public String             competency          {get; private set;}      
      public Boolean            hasAnchor           {get; private set;}
      public List<Question__c>  questions           {get; private set;}
      public List<Anchor__c>    anchorsUnfavorable  {get; private set;}
      public List<Anchor__c>    anchorsAcceptable   {get; private set;}
      public List<Anchor__c>    anchorsFavorable    {get; private set;}                  

    /**
     *      @desc:    Ctor. gets section settings and constructing the object.
     *      @param    sectionSettings: data about the section (including anchors)
     *      @return   section data
     */
      public SectionData(Interview_Section_Settings__c sectionSettings) {
        this.sectionIntro = sectionSettings.Intro__c;
        this.competency = sectionSettings.Competency__c;
        this.hasAnchor = sectionSettings.Has_Anchor__c;
        this.questions = getQuestions(sectionSettings.Assessor__c, sectionSettings.Competency__c);
        if (sectionSettings.Has_Anchor__c) {
          this.anchorsUnfavorable = getAnchors(sectionSettings.Assessor__c, sectionSettings.Competency__c, Label.Interview_Unfavorable);   
          this.anchorsAcceptable = getAnchors(sectionSettings.Assessor__c, sectionSettings.Competency__c, Label.Interview_Acceptable);     
          this.anchorsFavorable = getAnchors(sectionSettings.Assessor__c, sectionSettings.Competency__c, Label.Interview_Favorable);              
        }
      }

    /**
     *      @desc:    getting list of anchors for section
     *      @param    assessor: the interview record type
     *      @param    competency: the section type
     *      @param    scoreArea: favorable, unfavorable or acceptable 
     *      @return   list of anchors of the same scorearea
     */
      private List<Anchor__c> getAnchors(String assessor, String competency, String scoreArea) {
        return [SELECT Id, Anchor__c FROM Anchor__c WHERE Assessor__c =: assessor AND Competency__c =: competency AND Score_Area__c =: scoreArea AND Active__c=True];
      }

    /**
     *      @desc:    getting list of questions for section 
     *      @param    assessor: the interview record type
     *      @param    competency: the section type
     *      @return   list of questions for the section
     */
      private List<Question__c> getQuestions(String assessor, String competency) {
        return [SELECT Id, Sub_Area__c, Question__c FROM Question__c WHERE Assessor__c =: assessor AND Competency__c =: competency AND Active__C=True ORDER BY Sub_Area__c];
      }
    }

    /**
     *      @desc:    indicating that the page is on edit mode
     */
    public void editInterview() {
        editMode = true;
    }

    /**
     *      @desc:    saving the interview record 
     *      @param    interview: the interview details from the page
     *      @return   string to be displayed on the page popup
     */
    @remoteAction
    public static String saveInterview(Interview__c interview) {
        String retVal = 'ok';
        system.debug('interview @  saveInterview: ' + interview);
        try {
            upsert(interview);        
        } catch (Exception e) {
            system.debug('e.getMessage @  saveInterview: ' + e.getMessage());
            retVal = Label.Interview_Error_Occured + ' ' + e.getMessage();
        }
        return retVal;
    }
}