Selection Tookit package v1/retrieveOutput/objects/Anchor__c.object
<CustomObject>
    <description>This object include pre-defined anchors</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Anchor__c</fullName>
        <label>Anchor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessor__c</fullName>
        <label>Assessor</label>
        <picklist>
            <picklistValues>
                <fullName>People Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hiring Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Key Challenger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cultural Bar Raiser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Function</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EBM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Competency__c</fullName>
        <label>Competency</label>
        <picklist>
            <picklistValues>
                <fullName>Introduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dream Big</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Develop People</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live Our Culture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interest And Ambition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Functional Achievements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry Knowledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Socio Economic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecting The Dots</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Functional Challenge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Score_Area__c</fullName>
        <label>Score Area</label>
        <picklist>
            <picklistValues>
                <fullName>Unfavorable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acceptable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Favorable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Anchor</label>
    <nameField>
        <displayFormat>ANC-{0000}</displayFormat>
        <label>Anchor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Anchors</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Selection Tookit package v1/retrieveOutput/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Bands__c</fullName>
        <label>Bands</label>
        <picklist>
            <picklistValues>
                <fullName>EBM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I-A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I-B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>II-A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>II-B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>III-A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>III-B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IV-A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IV-B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V-A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V-B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VI-A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VI-B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VII-A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VII-B</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Candidate_Name__c</fullName>
        <description>Enter the name of the candidate</description>
        <label>Candidate Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <description>Enter Office</description>
        <label>Office</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Enter phonenumber</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Enter position</description>
        <label>Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Application Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People Manager Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hiring Manager Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Key Challenger Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cultural Bar Raiser Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Function Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EBM Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candidate Hired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candidate Did Not Pass</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CAN-{000000}</displayFormat>
        <label>Candidate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Selection Tookit package v1/retrieveOutput/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Function__c</fullName>
        <label>Function</label>
        <picklist>
            <picklistValues>
                <fullName>DGO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal/CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supply</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Position_Name__c</fullName>
        <label>Position Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Position</label>
    <nameField>
        <displayFormat>POS-{000000}</displayFormat>
        <label>Position Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Selection Tookit package v1/retrieveOutput/objects/Question__c.object
<CustomObject>
    <description>This object include pre-defined questions</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assessor__c</fullName>
        <label>Assessor</label>
        <picklist>
            <picklistValues>
                <fullName>People Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hiring Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Key Challenger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cultural Bar Raiser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Function</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EBM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Competency__c</fullName>
        <label>Competency</label>
        <picklist>
            <picklistValues>
                <fullName>Introduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dream Big</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Develop People</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live Our Culture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interest And Ambition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Functional Achievements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry Knowledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Socio Economic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecting The Dots</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Functional Challenge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insights</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Area__c</fullName>
        <label>Sub Area</label>
        <picklist>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Option 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Option 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Option 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Option 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Option 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Option 6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Selection Tookit package v1/retrieveOutput/classes/TestDataFactory.cls
public class TestDataFactory {
    
    
    
    public static List<User> createuserrecord() {   
            Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
            List<User> Users = new List<User>();
            User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='Test Candidate');
        return Users;
    }
    

    public static List<Candidate__c> createcandidaterecord() 
    {
        List<Candidate__c> candidates = new List<Candidate__c>();
        Candidate__c candidate = new Candidate__c(Candidate_Name__c='Test Candidate',Email__c='test.candidate@yahooo.com',Phone__c='1-234-55643', Bands__c='III-A', Office__c='NewYork', Position__c='Sales Manager', Status__c='Application Open');
        return candidates;
    }  
    
    public static List<Position__c> createpositionrecord() 
    {
        List<Position__c> positions = new List<Position__c>();
        Position__c position = new Position__c(Position_Name__c='Sales Manager',Role__c='Manager',Status__c='Open', Function__c='Sales', Description__c='This field contains description');
        return positions;
    }  
    
    public static List<Question__c> createquestionrecords() 
    {
        List<Question__c> questions = new List<Question__c>();
        Question__c question = new Question__c(Active__c=True,Assessor__c='People Manager',Competency__c='Introduction', Sub_Area__c='Lead', Question__c='In 2 minutes, walk me through your resume by highlighting your top achievements');
        questions.add(question);
        questions.add(new Question__c(Active__c=True,Assessor__c='People Manager',Competency__c='Dream Big', Sub_Area__c='Option 1', Question__c='What is your biggest achievement to date? (can be personal or professional)'));
        questions.add(new Question__c(Active__c=True,Assessor__c='People Manager',Competency__c='Develop People', Sub_Area__c='Option 1', Question__c='What are the qualities of a favorite leader that you have had?'));
        questions.add(new Question__c(Active__c=True,Assessor__c='People Manager',Competency__c='Interest And Ambition', Sub_Area__c='Option 1', Question__c='What are your long term career objectives? How do you plan on getting there?'));
        questions.add(new Question__c(Active__c=True,Assessor__c='Hiring Manager',Competency__c='Introduction', Sub_Area__c='Lead', Question__c='What is your biggest achievement to date? (can be personal or professional)'));
        questions.add(new Question__c(Active__c=True,Assessor__c='Hiring Manager',Competency__c='Functional Achievements', Sub_Area__c='Lead', Question__c='What are the qualities of a favorite leader that you have had?'));
        questions.add(new Question__c(Active__c=True,Assessor__c='Hiring Manager',Competency__c='Functional Achievements', Sub_Area__c='Option 1', Question__c='What are your long term career objectives? How do you plan on getting there?'));
        questions.add(new Question__c(Active__c=True,Assessor__c='Key Challenger',Competency__c='Introduction', Sub_Area__c='Lead', Question__c='What are your long term career objectives? How do you plan on getting there?'));
        questions.add(new Question__c(Active__c=True,Assessor__c='Key Challenger',Competency__c='Industry Knowledge', Sub_Area__c='Option 1', Question__c='What is your biggest achievement to date? (can be personal or professional)'));
        questions.add(new Question__c(Active__c=True,Assessor__c='Key Challenger',Competency__c='Socio Economic', Sub_Area__c='Option 1', Question__c='What are the qualities of a favorite leader that you have had?'));
        questions.add(new Question__c(Active__c=True,Assessor__c='Key Challenger',Competency__c='Connecting The Dots', Sub_Area__c='Option 1', Question__c='What are your long term career objectives? How do you plan on getting there?'));
        questions.add(new Question__c(Active__c=True,Assessor__c='Key Challenger',Competency__c='Functional Challenge', Sub_Area__c='Option 1', Question__c='What are your long term career objectives? How do you plan on getting there?'));
        questions.add(new Question__c(Active__c=True,Assessor__c='Cultural Bar Raiser',Competency__c='Introduction', Sub_Area__c='Lead', Question__c='What are your long term career objectives? How do you plan on getting there?'));
        questions.add(new Question__c(Active__c=True,Assessor__c='Cultural Bar Raiser',Competency__c='Dream Big', Sub_Area__c='Option 1', Question__c='What is your biggest achievement to date? (can be personal or professional)'));
        questions.add(new Question__c(Active__c=True,Assessor__c='Cultural Bar Raiser',Competency__c='Develop People', Sub_Area__c='Option 1', Question__c='What are the qualities of a favorite leader that you have had?'));
        questions.add(new Question__c(Active__c=True,Assessor__c='Cultural Bar Raiser',Competency__c='Live Our Culture', Sub_Area__c='Option 1', Question__c='What are your long term career objectives? How do you plan on getting there?'));
        questions.add(new Question__c(Active__c=True,Assessor__c='Head of Function',Competency__c='Introduction', Sub_Area__c='Option 1', Question__c='What are your long term career objectives? How do you plan on getting there?'));
        questions.add(new Question__c(Active__c=True,Assessor__c='Head of Function',Competency__c='Dream Big', Sub_Area__c='Option 1', Question__c='What is your biggest achievement to date? (can be personal or professional)'));
        questions.add(new Question__c(Active__c=True,Assessor__c='Head of Function',Competency__c='Develop People', Sub_Area__c='Option 1', Question__c='What are the qualities of a favorite leader that you have had?'));
        questions.add(new Question__c(Active__c=True,Assessor__c='Head of Function',Competency__c='Live Our Culture', Sub_Area__c='Option 1', Question__c='What are your long term career objectives? How do you plan on getting there?'));
        questions.add(new Question__c(Active__c=True,Assessor__c='Head of Function',Competency__c='Insights', Sub_Area__c='Option 1', Question__c='What are your long term career objectives? How do you plan on getting there?'));
        questions.add(new Question__c(Active__c=True,Assessor__c='EBM',Competency__c='Introduction', Sub_Area__c='Option 1', Question__c='What are your long term career objectives? How do you plan on getting there?'));
        questions.add(new Question__c(Active__c=True,Assessor__c='EBM',Competency__c='Dream Big', Sub_Area__c='Option 1', Question__c='What is your biggest achievement to date? (can be personal or professional)'));
        questions.add(new Question__c(Active__c=True,Assessor__c='EBM',Competency__c='Develop People', Sub_Area__c='Option 1', Question__c='What are the qualities of a favorite leader that you have had?'));
        questions.add(new Question__c(Active__c=True,Assessor__c='EBM',Competency__c='Live Our Culture', Sub_Area__c='Option 1', Question__c='What are your long term career objectives? How do you plan on getting there?'));
        return questions;
    } 
    
    public static List<Anchor__c> createanchorrecords() 
    {
        List<Anchor__c> anchors = new List<Anchor__c>();
        Anchor__c anchor = new Anchor__c(Active__c=True,Assessor__c='People Manager',Competency__c='Dream Big',Score_Area__c='Unfavorable',  Anchor__c='Unable to describe relatively specific achievement');
        anchors.add(anchor);
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='People Manager',Competency__c='Dream Big',Score_Area__c='Acceptable',  Anchor__c='Provided performance or results-oriented accomplishment '));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='People Manager',Competency__c='Dream Big',Score_Area__c='Favorable',  Anchor__c='Sets the bar high and is never happy with the status quo'));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='People Manager',Competency__c='Develop People',Score_Area__c='Unfavorable',  Anchor__c='Provided performance or results-oriented accomplishment '));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='People Manager',Competency__c='Develop People',Score_Area__c='Acceptable',  Anchor__c='Sets the bar high and is never happy with the status quo'));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='People Manager',Competency__c='Develop People',Score_Area__c='Favorable',  Anchor__c='Provided performance or results-oriented accomplishment '));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='People Manager',Competency__c='Interest And Ambition',Score_Area__c='Unfavorable',  Anchor__c='Provided performance or results-oriented accomplishment '));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='People Manager',Competency__c='Interest And Ambition',Score_Area__c='Acceptable',  Anchor__c='Sets the bar high and is never happy with the status quo'));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='People Manager',Competency__c='Interest And Ambition',Score_Area__c='Favorable',  Anchor__c='Provided performance or results-oriented accomplishment '));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Hiring Manager',Competency__c='Functional Achievements',Score_Area__c='Unfavorable',  Anchor__c='Provided performance or results-oriented accomplishment '));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Hiring Manager',Competency__c='Functional Achievements',Score_Area__c='Acceptable',  Anchor__c='Sets the bar high and is never happy with the status quo'));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Hiring Manager',Competency__c='Functional Achievements',Score_Area__c='Favorable',  Anchor__c='Provided performance or results-oriented accomplishment '));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Cultural Bar Raiser',Competency__c='Dream Big',Score_Area__c='Unfavorable',  Anchor__c='Provided performance or results-oriented accomplishment '));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Cultural Bar Raiser',Competency__c='Dream Big',Score_Area__c='Acceptable',  Anchor__c='Sets the bar high and is never happy with the status quo'));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Cultural Bar Raiser',Competency__c='Dream Big',Score_Area__c='Favorable',  Anchor__c='Provided performance or results-oriented accomplishment '));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Cultural Bar Raiser',Competency__c='Develop People',Score_Area__c='Unfavorable',  Anchor__c='Provided performance or results-oriented accomplishment '));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Cultural Bar Raiser',Competency__c='Develop People',Score_Area__c='Acceptable',  Anchor__c='Sets the bar high and is never happy with the status quo'));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Cultural Bar Raiser',Competency__c='Develop People',Score_Area__c='Favorable',  Anchor__c='Provided performance or results-oriented accomplishment '));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Cultural Bar Raiser',Competency__c='Live Our Culture',Score_Area__c='Unfavorable',  Anchor__c='Provided performance or results-oriented accomplishment '));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Cultural Bar Raiser',Competency__c='Live Our Culture',Score_Area__c='Acceptable',  Anchor__c='Sets the bar high and is never happy with the status quo'));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Cultural Bar Raiser',Competency__c='Live Our Culture',Score_Area__c='Favorable',  Anchor__c='Provided performance or results-oriented accomplishment '));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Head of Function',Competency__c='Dream Big',Score_Area__c='Unfavorable',  Anchor__c='Provided performance or results-oriented accomplishment '));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Head of Function',Competency__c='Dream Big',Score_Area__c='Acceptable',  Anchor__c='Sets the bar high and is never happy with the status quo'));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Head of Function',Competency__c='Dream Big',Score_Area__c='Favorable',  Anchor__c='Provided performance or results-oriented accomplishment '));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Head of Function',Competency__c='Develop People',Score_Area__c='Unfavorable',  Anchor__c='Provided performance or results-oriented accomplishment '));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Head of Function',Competency__c='Develop People',Score_Area__c='Acceptable',  Anchor__c='Sets the bar high and is never happy with the status quo'));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Head of Function',Competency__c='Develop People',Score_Area__c='Favorable',  Anchor__c='Provided performance or results-oriented accomplishment '));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Head of Function',Competency__c='Live Our Culture',Score_Area__c='Unfavorable',  Anchor__c='Provided performance or results-oriented accomplishment '));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Head of Function',Competency__c='Live Our Culture',Score_Area__c='Acceptable',  Anchor__c='Sets the bar high and is never happy with the status quo'));
        anchors.add(new Anchor__c(Active__c=True,Assessor__c='Head of Function',Competency__c='Live Our Culture',Score_Area__c='Favorable',  Anchor__c='Provided performance or results-oriented accomplishment '));
        return anchors;
    } 
    
    
}