Selection Tookit package v1/retrieveOutput/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Bands__c</fullName>
        <label>Bands</label>
        <picklist>
            <picklistValues>
                <fullName>EBM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I-A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I-B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>II-A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>II-B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>III-A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>III-B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IV-A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IV-B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V-A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V-B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VI-A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VI-B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VII-A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VII-B</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Candidate_Name__c</fullName>
        <description>Enter the name of the candidate</description>
        <label>Candidate Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <description>Enter Office</description>
        <label>Office</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Enter phonenumber</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Enter position</description>
        <label>Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Application Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People Manager Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hiring Manager Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Key Challenger Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cultural Bar Raiser Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Function Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EBM Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candidate Hired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candidate Did Not Pass</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CAN-{000000}</displayFormat>
        <label>Candidate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Selection Tookit package v1/retrieveOutput/objects/Interview__c.object
<CustomObject>
    <description>This object include interview records</description>
    <fields>
        <fullName>Candidate_Name__c</fullName>
        <label>Candidate Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Interviews</relationshipLabel>
        <relationshipName>Interviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Interviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position_Name__c</fullName>
        <label>Position Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Interviews</relationshipLabel>
        <relationshipName>Interviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Interview</label>
    <nameField>
        <displayFormat>INT-{0000000}</displayFormat>
        <label>Interview Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <recordTypes>
        <fullName>EBM</fullName>
        <active>true</active>
        <label>EBM</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Selection Tookit package v1/retrieveOutput/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Function__c</fullName>
        <label>Function</label>
        <picklist>
            <picklistValues>
                <fullName>DGO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal/CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supply</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Position_Name__c</fullName>
        <label>Position Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Position</label>
    <nameField>
        <displayFormat>POS-{000000}</displayFormat>
        <label>Position Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Selection Tookit package v1/retrieveOutput/classes/TestInterview_Record.cls
@isTest
public class TestInterview_Record {
    String CandidateId;
    
    @isTest static void TestInterviewRecordCandidateStatusPeopleManager() {
   
   
   
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        
        list<User> users = new list<User>();
        User campRep1 = new User(Alias = 'cmprep1', Email='campusrep1@testorg1234.com', 
                          EmailEncodingKey='UTF-8', LastName='Rep', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='camprep1@testorg1234.com',
                          Band__c = 'I', Function__c = 'Sales', University__c = 'Duke', Talent_Program__c = 'GMT', Flexible_Scheduling__c = 'Yes'); 
        users.add(campRep1);
        
        insert users;
        
        List<Position__c> positions = new List<Position__c>();
        Position__c position = new Position__c(Position_Name__c='Sales Manager',Role__c='Manager',Status__c='Open', Function__c='Sales', Description__c='This field contains description');
        positions.add(position);
        insert positions;
        
        List<Candidate__c> candidates = new List<Candidate__c>();
        Candidate__c candidate = new Candidate__c(Candidate_Name__c='Test Candidate',Email__c='test.candidate@yahooo.com',Phone__c='1-234-55643', Bands__c='III-A', Office__c='NewYork', Position__c='Sales Manager', Status__c='Application Open');
        candidates.add(candidate);
        insert candidates;
        
        
        
        
        String CandidateId;
        String InterviewerId;
        String PositionId;
        
        LIST <Position__c> GetPositionId = [SELECT Id
                               FROM Position__c
                                       WHERE  Position_Name__c='Sales Manager'];
            
               for(Position__c getposition_record: GetPositionId){
                    PositionId=getposition_record.Id;
             
               }
        
        
        LIST <Candidate__c> GetCandidateId = [SELECT Id
                               FROM Candidate__c
                                       WHERE  Candidate_Name__c='Test Candidate'];
            
               for(Candidate__c getcandidate_record: GetCandidateId){
                    CandidateId=getcandidate_record.Id;
             
               }
        
         LIST <User> GetInterviewerId = [SELECT Id
                               FROM User
                                       WHERE  UserName='camprep1@testorg1234.com'];
            
               for(User getinterviewer_record: GetInterviewerId){
                    InterviewerId=getinterviewer_record.Id;
             
               }
        
        System.debug('Candidate ID: ' + CandidateId);
        System.debug('Interview ID: ' + InterviewerId);
        List<Interview__C> interviews = new List<Interview__C>();
        Interview__C interview = new Interview__C(RecordTypeId ='012630000004JoIAAU', Candidate__c=CandidateId, Interviewer__C=InterviewerId, Position__c=PositionId);
        interviews.add(interview);
        insert interviews;
        
        
        Test.startTest();
        
            LIST <Candidate__c> Candidatess = [SELECT Candidate_Name__c, Status__c
                               FROM Candidate__c
                                       WHERE  Candidate_Name__c='Test Candidate'];
            
               for(Candidate__c candidate_record: Candidatess){
                   System.assert(candidate_record.Status__c =='People Manager Interview');
               
               }
        
        LIST <Interview__c> Interviewss = [SELECT OwnerId, Position_Name__c
                               FROM Interview__c
                                       WHERE  Candidate__c=:CandidateId];
            
               for(Interview__c interview_record: Interviewss){
                   System.debug('Interview Record: ' + interview_record);
                   System.assert(interview_record.OwnerId==InterviewerId);
                   System.assert(interview_record.Position_Name__c=='Sales Manager');
               }
        
      
        
        
        
Test.stopTest();
        
}
    
    @isTest static void TestInterviewRecordCandidateStatusHiringManager() {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];       
        list<User> users = new list<User>();
        User campRep1 = new User(Alias = 'cmprep1', Email='campusrep1@testorg1234.com', 
                          EmailEncodingKey='UTF-8', LastName='Rep', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='camprep1@testorg1234.com',
                          Band__c = 'I', Function__c = 'Sales', University__c = 'Duke', Talent_Program__c = 'GMT', Flexible_Scheduling__c = 'Yes'); 
        users.add(campRep1);       
        insert users;
        
        List<Position__c> positions = new List<Position__c>();
        Position__c position = new Position__c(Position_Name__c='Sales Manager',Role__c='Manager',Status__c='Open', Function__c='Sales', Description__c='This field contains description');
        positions.add(position);
        insert positions;
        
        List<Candidate__c> candidates = new List<Candidate__c>();
        Candidate__c candidate = new Candidate__c(Candidate_Name__c='Test Candidate',Email__c='test.candidate@yahooo.com',Phone__c='1-234-55643', Bands__c='III-A', Office__c='NewYork', Position__c='Sales Manager', Status__c='Application Open');
        candidates.add(candidate);
        insert candidates;

        String CandidateId;
        String InterviewerId;
        String PositionId;
        
        LIST <Position__c> GetPositionId = [SELECT Id
                               FROM Position__c
                                       WHERE  Position_Name__c='Sales Manager'];
            
               for(Position__c getposition_record: GetPositionId){
                    PositionId=getposition_record.Id;
             
               }
        LIST <Candidate__c> GetCandidateId = [SELECT Id
                               FROM Candidate__c
                                       WHERE  Candidate_Name__c='Test Candidate'];
            
               for(Candidate__c getcandidate_record: GetCandidateId){
                    CandidateId=getcandidate_record.Id;
             
               }
        
         LIST <User> GetInterviewerId = [SELECT Id
                               FROM User
                                       WHERE  UserName='camprep1@testorg1234.com'];
            
               for(User getinterviewer_record: GetInterviewerId){
                    InterviewerId=getinterviewer_record.Id;
             
               }
        
        System.debug('Candidate ID: ' + CandidateId);
        System.debug('Interview ID: ' + InterviewerId);
        List<Interview__C> interviews = new List<Interview__C>();
        Interview__C interview = new Interview__C(RecordTypeId ='012630000004JoN', Candidate__c=CandidateId, Interviewer__C=InterviewerId, Position__c=PositionId);
        interviews.add(interview);
        insert interviews;
  
        Test.startTest();
        
            LIST <Candidate__c> Candidatess = [SELECT Candidate_Name__c, Status__c
                               FROM Candidate__c
                                       WHERE  Candidate_Name__c='Test Candidate'];
            
               for(Candidate__c candidate_record: Candidatess){
                   System.assert(candidate_record.Status__c =='Hiring Manager Interview');
               
               }
        
        LIST <Interview__c> Interviewss = [SELECT OwnerId, Position_Name__c
                               FROM Interview__c
                                       WHERE  Candidate__c=:CandidateId];
            
               for(Interview__c interview_record: Interviewss){
                   System.debug('Interview Record: ' + interview_record);
                   System.assert(interview_record.OwnerId==InterviewerId);
                   System.assert(interview_record.Position_Name__c=='Sales Manager');
               }
    
Test.stopTest();
        
}
        @isTest static void TestInterviewRecordCandidateKeyChallengerInterview() {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];       
        list<User> users = new list<User>();
        User campRep1 = new User(Alias = 'cmprep1', Email='campusrep1@testorg1234.com', 
                          EmailEncodingKey='UTF-8', LastName='Rep', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='camprep1@testorg1234.com',
                          Band__c = 'I', Function__c = 'Sales', University__c = 'Duke', Talent_Program__c = 'GMT', Flexible_Scheduling__c = 'Yes'); 
        users.add(campRep1);       
        insert users;
        
        List<Position__c> positions = new List<Position__c>();
        Position__c position = new Position__c(Position_Name__c='Sales Manager',Role__c='Manager',Status__c='Open', Function__c='Sales', Description__c='This field contains description');
        positions.add(position);
        insert positions;
        
        List<Candidate__c> candidates = new List<Candidate__c>();
        Candidate__c candidate = new Candidate__c(Candidate_Name__c='Test Candidate',Email__c='test.candidate@yahooo.com',Phone__c='1-234-55643', Bands__c='III-A', Office__c='NewYork', Position__c='Sales Manager', Status__c='Application Open');
        candidates.add(candidate);
        insert candidates;

        String CandidateId;
        String InterviewerId;
        String PositionId;
        
        LIST <Position__c> GetPositionId = [SELECT Id
                               FROM Position__c
                                       WHERE  Position_Name__c='Sales Manager'];
            
               for(Position__c getposition_record: GetPositionId){
                    PositionId=getposition_record.Id;
             
               }
        LIST <Candidate__c> GetCandidateId = [SELECT Id
                               FROM Candidate__c
                                       WHERE  Candidate_Name__c='Test Candidate'];
            
               for(Candidate__c getcandidate_record: GetCandidateId){
                    CandidateId=getcandidate_record.Id;
             
               }
        
         LIST <User> GetInterviewerId = [SELECT Id
                               FROM User
                                       WHERE  UserName='camprep1@testorg1234.com'];
            
               for(User getinterviewer_record: GetInterviewerId){
                    InterviewerId=getinterviewer_record.Id;
             
               }
        
        System.debug('Candidate ID: ' + CandidateId);
        System.debug('Interview ID: ' + InterviewerId);
        List<Interview__C> interviews = new List<Interview__C>();
        Interview__C interview = new Interview__C(RecordTypeId ='012630000004JoS', Candidate__c=CandidateId, Interviewer__C=InterviewerId, Position__c=PositionId);
        interviews.add(interview);
        insert interviews;
  
        Test.startTest();
        
            LIST <Candidate__c> Candidatess = [SELECT Candidate_Name__c, Status__c
                               FROM Candidate__c
                                       WHERE  Candidate_Name__c='Test Candidate'];
            
               for(Candidate__c candidate_record: Candidatess){
                   System.assert(candidate_record.Status__c =='Key Challenger Interview');
               
               }
        
        LIST <Interview__c> Interviewss = [SELECT OwnerId, Position_Name__c
                               FROM Interview__c
                                       WHERE  Candidate__c=:CandidateId];
            
               for(Interview__c interview_record: Interviewss){
                   System.debug('Interview Record: ' + interview_record);
                   System.assert(interview_record.OwnerId==InterviewerId);
                   System.assert(interview_record.Position_Name__c=='Sales Manager');
               
               }
    
Test.stopTest();
        
}
        @isTest static void TestInterviewRecordCandidateStatusCulturalBarRaiserInterview() {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];       
        list<User> users = new list<User>();
        User campRep1 = new User(Alias = 'cmprep1', Email='campusrep1@testorg1234.com', 
                          EmailEncodingKey='UTF-8', LastName='Rep', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='camprep1@testorg1234.com',
                          Band__c = 'I', Function__c = 'Sales', University__c = 'Duke', Talent_Program__c = 'GMT', Flexible_Scheduling__c = 'Yes'); 
        users.add(campRep1);       
        insert users;
        
        List<Position__c> positions = new List<Position__c>();
        Position__c position = new Position__c(Position_Name__c='Sales Manager',Role__c='Manager',Status__c='Open', Function__c='Sales', Description__c='This field contains description');
        positions.add(position);
        insert positions;
        
        List<Candidate__c> candidates = new List<Candidate__c>();
        Candidate__c candidate = new Candidate__c(Candidate_Name__c='Test Candidate',Email__c='test.candidate@yahooo.com',Phone__c='1-234-55643', Bands__c='III-A', Office__c='NewYork', Position__c='Sales Manager', Status__c='Application Open');
        candidates.add(candidate);
        insert candidates;

        String CandidateId;
        String InterviewerId;
        String PositionId;
        
        LIST <Position__c> GetPositionId = [SELECT Id
                               FROM Position__c
                                       WHERE  Position_Name__c='Sales Manager'];
            
               for(Position__c getposition_record: GetPositionId){
                    PositionId=getposition_record.Id;
             
               }
        LIST <Candidate__c> GetCandidateId = [SELECT Id
                               FROM Candidate__c
                                       WHERE  Candidate_Name__c='Test Candidate'];
            
               for(Candidate__c getcandidate_record: GetCandidateId){
                    CandidateId=getcandidate_record.Id;
             
               }
        
         LIST <User> GetInterviewerId = [SELECT Id
                               FROM User
                                       WHERE  UserName='camprep1@testorg1234.com'];
            
               for(User getinterviewer_record: GetInterviewerId){
                    InterviewerId=getinterviewer_record.Id;
             
               }
        
        System.debug('Candidate ID: ' + CandidateId);
        System.debug('Interview ID: ' + InterviewerId);
        List<Interview__C> interviews = new List<Interview__C>();
        Interview__C interview = new Interview__C(RecordTypeId ='012630000004JoX', Candidate__c=CandidateId, Interviewer__C=InterviewerId, Position__c=PositionId);
        interviews.add(interview);
        insert interviews;
  
        Test.startTest();
        
            LIST <Candidate__c> Candidatess = [SELECT Candidate_Name__c, Status__c
                               FROM Candidate__c
                                       WHERE  Candidate_Name__c='Test Candidate'];
            
               for(Candidate__c candidate_record: Candidatess){
                   System.assert(candidate_record.Status__c =='Cultural Bar Raiser Interview');
               
               }
        
        LIST <Interview__c> Interviewss = [SELECT OwnerId, Position_Name__c
                               FROM Interview__c
                                       WHERE  Candidate__c=:CandidateId];
            
               for(Interview__c interview_record: Interviewss){
                   System.debug('Interview Record: ' + interview_record);
                   System.assert(interview_record.OwnerId==InterviewerId);
                   System.assert(interview_record.Position_Name__c=='Sales Manager');
               }
    
Test.stopTest();
        
}
        @isTest static void TestInterviewRecordCandidateStatusHeadofFunctionInterview() {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];       
        list<User> users = new list<User>();
        User campRep1 = new User(Alias = 'cmprep1', Email='campusrep1@testorg1234.com', 
                          EmailEncodingKey='UTF-8', LastName='Rep', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='camprep1@testorg1234.com',
                          Band__c = 'I', Function__c = 'Sales', University__c = 'Duke', Talent_Program__c = 'GMT', Flexible_Scheduling__c = 'Yes'); 
        users.add(campRep1);       
        insert users;
        
        List<Position__c> positions = new List<Position__c>();
        Position__c position = new Position__c(Position_Name__c='Sales Manager',Role__c='Manager',Status__c='Open', Function__c='Sales', Description__c='This field contains description');
        positions.add(position);
        insert positions;
        
        List<Candidate__c> candidates = new List<Candidate__c>();
        Candidate__c candidate = new Candidate__c(Candidate_Name__c='Test Candidate',Email__c='test.candidate@yahooo.com',Phone__c='1-234-55643', Bands__c='III-A', Office__c='NewYork', Position__c='Sales Manager', Status__c='Application Open');
        candidates.add(candidate);
        insert candidates;

        String CandidateId;
        String InterviewerId;
        String PositionId;
        
        LIST <Position__c> GetPositionId = [SELECT Id
                               FROM Position__c
                                       WHERE  Position_Name__c='Sales Manager'];
            
               for(Position__c getposition_record: GetPositionId){
                    PositionId=getposition_record.Id;
             
               }
        LIST <Candidate__c> GetCandidateId = [SELECT Id
                               FROM Candidate__c
                                       WHERE  Candidate_Name__c='Test Candidate'];
            
               for(Candidate__c getcandidate_record: GetCandidateId){
                    CandidateId=getcandidate_record.Id;
             
               }
        
         LIST <User> GetInterviewerId = [SELECT Id
                               FROM User
                                       WHERE  UserName='camprep1@testorg1234.com'];
            
               for(User getinterviewer_record: GetInterviewerId){
                    InterviewerId=getinterviewer_record.Id;
             
               }
        
        System.debug('Candidate ID: ' + CandidateId);
        System.debug('Interview ID: ' + InterviewerId);
        List<Interview__C> interviews = new List<Interview__C>();
        Interview__C interview = new Interview__C(RecordTypeId ='012630000004Joc', Candidate__c=CandidateId, Interviewer__C=InterviewerId, Position__c=PositionId);
        interviews.add(interview);
        insert interviews;
  
        Test.startTest();
        
            LIST <Candidate__c> Candidatess = [SELECT Candidate_Name__c, Status__c
                               FROM Candidate__c
                                       WHERE  Candidate_Name__c='Test Candidate'];
            
               for(Candidate__c candidate_record: Candidatess){
                   System.assert(candidate_record.Status__c =='Head of Function Interview');
               
               }
        
        LIST <Interview__c> Interviewss = [SELECT OwnerId, Position_Name__c
                               FROM Interview__c
                                       WHERE  Candidate__c=:CandidateId];
            
               for(Interview__c interview_record: Interviewss){
                   System.debug('Interview Record: ' + interview_record);
                   System.assert(interview_record.OwnerId==InterviewerId);
                   System.assert(interview_record.Position_Name__c=='Sales Manager');
               }
    
Test.stopTest();
        
}
        @isTest static void TestInterviewRecordCandidateStatusEBMInterview() {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];       
        list<User> users = new list<User>();
        User campRep1 = new User(Alias = 'cmprep1', Email='campusrep1@testorg1234.com', 
                          EmailEncodingKey='UTF-8', LastName='Rep', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='camprep1@testorg1234.com',
                          Band__c = 'I', Function__c = 'Sales', University__c = 'Duke', Talent_Program__c = 'GMT', Flexible_Scheduling__c = 'Yes'); 
        users.add(campRep1);       
        insert users;
        
        List<Position__c> positions = new List<Position__c>();
        Position__c position = new Position__c(Position_Name__c='Sales Manager',Role__c='Manager',Status__c='Open', Function__c='Sales', Description__c='This field contains description');
        positions.add(position);
        insert positions;
        
        List<Candidate__c> candidates = new List<Candidate__c>();
        Candidate__c candidate = new Candidate__c(Candidate_Name__c='Test Candidate',Email__c='test.candidate@yahooo.com',Phone__c='1-234-55643', Bands__c='III-A', Office__c='NewYork', Position__c='Sales Manager', Status__c='Application Open');
        candidates.add(candidate);
        insert candidates;

        String CandidateId;
        String InterviewerId;
        String PositionId;
        
        LIST <Position__c> GetPositionId = [SELECT Id
                               FROM Position__c
                                       WHERE  Position_Name__c='Sales Manager'];
            
               for(Position__c getposition_record: GetPositionId){
                    PositionId=getposition_record.Id;
             
               }
        LIST <Candidate__c> GetCandidateId = [SELECT Id
                               FROM Candidate__c
                                       WHERE  Candidate_Name__c='Test Candidate'];
            
               for(Candidate__c getcandidate_record: GetCandidateId){
                    CandidateId=getcandidate_record.Id;
             
               }
        
         LIST <User> GetInterviewerId = [SELECT Id
                               FROM User
                                       WHERE  UserName='camprep1@testorg1234.com'];
            
               for(User getinterviewer_record: GetInterviewerId){
                    InterviewerId=getinterviewer_record.Id;
             
               }
        
        System.debug('Candidate ID: ' + CandidateId);
        System.debug('Interview ID: ' + InterviewerId);
        List<Interview__C> interviews = new List<Interview__C>();
        Interview__C interview = new Interview__C(RecordTypeId ='012630000004Joh', Candidate__c=CandidateId, Interviewer__C=InterviewerId, Position__c=PositionId);
        interviews.add(interview);
        insert interviews;
  
        Test.startTest();
        
            LIST <Candidate__c> Candidatess = [SELECT Candidate_Name__c, Status__c
                               FROM Candidate__c
                                       WHERE  Candidate_Name__c='Test Candidate'];
            
               for(Candidate__c candidate_record: Candidatess){
                   System.assert(candidate_record.Status__c =='EBM Interview');
               
               }
        
        LIST <Interview__c> Interviewss = [SELECT OwnerId, Position_Name__c
                               FROM Interview__c
                                       WHERE  Candidate__c=:CandidateId];
            
               for(Interview__c interview_record: Interviewss){
                   System.debug('Interview Record: ' + interview_record);
                   System.assert(interview_record.OwnerId==InterviewerId);
                   System.assert(interview_record.Position_Name__c=='Sales Manager');
               
               }
    
Test.stopTest();
        
}
    
    
    
    
    
    
    
}